version: "3.7"

services:
  elasticsearch:
    container_name: "local_elasticsearch"
    build: ./local/elasticsearch
    ports:
      - "9200:9200"
    networks:
      - elastic-tier
    # the following 2 params mean that is "-it" option of "docker run" command. it's to keep docker run.
    tty: true
    stdin_open: true
    # the following 2 params are to use systemctl command on centos.
    privileged: true
    command: /sbin/init

  kibana:
    container_name: "local_kibana"
    build: ./local/kibana
    ports:
      - "5601:5601"
    networks:
      - elastic-tier
    depends_on:
      - elasticsearch
    # the following 2 params mean that is "-it" option of "docker run" command. it's to keep docker run.
    tty: true
    stdin_open: true
    # the following 2 params are to use systemctl command on centos.
    privileged: true
    command: /sbin/init

  apm-server:
    container_name: "local_apm-server"
    build: ./local/apm-server
    ports:
      - "8200:8200"
    networks:
      - elastic-tier
      - apm-tier
    depends_on:
      - elasticsearch
    # the following 2 params mean that is "-it" option of "docker run" command. it's to keep docker run.
    tty: true
    stdin_open: true
    # the following 2 params are to use systemctl command on centos.
    privileged: true
    command: /sbin/init

# docker network create --driver bridge elasticstack
networks:
  elastic-tier:
    driver: bridge # default value, can be ommitted
    name: elastic-tier
  apm-tier: # the network that connect apm-server and apm-client
    driver: bridge
    name: apm-tier